[package]
name = "wgpu-glyph-debug"
version = "0.1.0"
authors = ["Michael Baker <michaeltbaker@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.4"
twox-hash = "1.5.0"
wgpu = "0.5.0"
wgpu_glyph = "0.8.0"
winit = "0.22.0"